### ISSUE TITLE
[BUG] Prisma Decimal gets converted into kysely String

### ISSUE THREAD

**Issue by wikes82** [valtyr/prisma-kysely#78] opened 2023-09-22 15:56 UTC
When converting Decimal type of prisma, it converted into string instead of number.

Sample Schema:
```
generator kysely {
  provider     = "prisma-kysely"
  output       = "../src/kyselydb"
  fileName     = "kysely-types.ts"
  enumFileName = "kysely-enums.ts"
}

generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "cockroachdb"
  url      = env("DEMODEV_DATABASE_URL")
}
model TestModel {
    id                   String             @id @default(dbgenerated("gen_random_uuid()")) @db.Uuid
   credit_rate      Decimal
}
```

the generated kysely types:
```
export type TestModel = {
	id: Generated<string>;
	credit_rate: string;
}
```

**Comment by wikes82** [comment] 2023-09-25 15:28
@valtyr No, the mapping on this file is wrong for postgresql and mysql -> https://github.com/valtyr/prisma-kysely/blob/main/src/helpers/generateFieldType.ts

**Comment by delight** [comment] 2023-09-26 21:49
I can confirm the behavior:

prisma:
`  expires         BigInt?`

results in kysely:
`	expires: string | null`

**Comment by cahnory** [comment] 2023-10-08 17:40
The node `pg` driver will in fact return a string for decimal and bigint types for technical reason (MAX_SAFE_INTEGER):
https://github.com/brianc/node-postgres/issues/811#issuecomment-116644535

You can setup pg driver to typecast numeric value:
```ts
import { types } from "pg";

types.setTypeParser(types.builtins.NUMERIC, (value) => Number(value));
```

And override types in your schema generator config:
```prisma
generator kysely {
  provider            = "prisma-kysely"
  output              = "../src/kyselydb"
  fileName            = "kysely-types.ts"
  enumFileName        = "kysely-enums.ts"
  decimalTypeOverride = "number"
  bigIntTypeOverride  = "number"
}
```

**Comment by delight** [comment] 2023-10-10 15:56
I understand the MAX_SAFE_INTEGER problem in JS - but right here I don't think that is the problem.

I assume if you'd have a BigInt or similar in the database and you wouldn't use string in the kysely-types definition.
And this is what this is about, translation of a prisma schema to kysely types.

**Comment by valtyr** [comment] 2023-11-01 10:27
@delight There's a file called src/dialectTests/postgresql.ts that runs a very simple test. It creates the database with all the types supported by prisma-kysely, queries all the fields, and prints out the `typeof` for all the fields. I used this to verify the types for each dialect when I wrote the initial versions of prisma-kysely. It confirms that the driver indeed returns a `string` type when querying a `BigInt`. Remember that prisma-kysely only operates in type land and has to be opinionated by default to support the types returned by the standard kysely driver for each dialect. If you want the string to be parsed into a BigInt object after a query, or if it turns out that you're using some non-standard driver or have configured it differently then I refer to @cahnory's solution above. If we were to change the type we would break prisma-kysely for everyone else. If you are interested in running the test for yourself, you can run `docker compose up -d postgres` in the root directory to boot a database and run `yarn run build && node dist/dialectTests/postgresql.js` to run the tests.

<img width="532" alt="CleanShot 2023-11-01 at 10 19 49@2x" src="https://github.com/valtyr/prisma-kysely/assets/3050355/d8b70d15-1cca-4b6b-8db7-0c06530d7cc0">

**Comment by valtyr** [comment] 2023-11-01 10:30
Oh and here are the results for mysql:

<img width="521" alt="CleanShot 2023-11-01 at 10 29 31@2x" src="https://github.com/valtyr/prisma-kysely/assets/3050355/09c4f662-7e75-4086-a8f2-622fb97e171e">

**Comment by valtyr** [comment] 2024-02-07 13:49
Closing this as per my comments above.

**Closed by valtyr** 2024-02-07 13:49 UTC
