### ISSUE TITLE
spawn prisma-kysely ENOENT

### ISSUE THREAD

**Issue by KhalilJouaneh** [valtyr/prisma-kysely#82] opened 2023-10-18 04:07 UTC
I'm getting this error when I run npx prisma generate. My primsa cli is up to date. 

Versions: 
    "prisma-kysely": "^1.7.1",
    "prisma": "^5.4.2"
    "kysely": "^0.26.3",

```
npx prisma generate      
Prisma schema loaded from prisma\schema.prisma
Error: 
spawn prisma-kysely ENOENT
```

Does anyone how to fix this pesky issue?

**Comment by henaff** [comment] 2023-10-26 08:14
Same issue for me

**Comment by fab0i** [comment] 2023-12-19 04:57
Try a global `prisma-kysely` install (See https://github.com/valtyr/prisma-kysely/issues/69#issuecomment-1820267566)
```npm i -g prisma-kysely```

**Comment by MrSharpp** [comment] 2023-12-24 12:36
same issue

**Comment by MrSharpp** [comment] 2023-12-24 12:44
found a fix for this issue,
this issue was arising due to importing of es6 module "string-width" into prisma-kysely dist files.
the quickest solution for me is to just remove all node_modules and then instead of using yarn i used pnpm and it installed correct peer dependency which somehow worked with prisma-kysely.

**Comment by tbui17** [comment] 2024-01-17 22:47
I'm not sure of the issue exactly, but it in my case it seemed to be related to my framework and bundler (Next.JS 13) build process and how the generator designates the output folder.

For me specifying the output dir explicitly in the generator configs fixes the issue.

**Comment by valtyr** [comment] 2024-05-08 01:02
Duplicate of #69

**Closed by valtyr** 2024-05-08 01:02 UTC
Labels: bug
